# Base image
FROM python:3.12-slim

# Create working directory
WORKDIR /app

# Copy dependency file
COPY requirements.txt .

# Install Python packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app.py .

# Expose application port
EXPOSE 5001

# Start the application
CMD ["python3", "app.py"]
